### ISSUE TITLE
Webhook posts same article every two hours

### ISSUE THREAD

**Issue by itswzyss** [Carbowix/newswire#2]
I've managed to get this working myself, however it seems that the database doesn't keep up with anything -- most likely a me thing though.

Using level 5.0.1

No indication of an error, there are ldb files in `newswire` folder.

**Comment by Carbowix** [comment]
Not sure actually why the db fails to detect if there's a replicate ID, but seems like there's a problem with the addition of the article in the database. Would be nice if you pull request the fix, since I don't have enough time to get into coding right now.

**Comment by Carbowix** [comment]
Issue has been solved, thanks for your report.
